### ISSUE TITLE
[AWS 사례분석] 1월5주차 - 정비공장&자동차 사고 & 보험처리 플랫폼

### ISSUE THREAD

**Issue by GwangHeon** [echoen/enjoy-aws#17]
아무리 짱돌을 굴려봐도 제가 찾으려는 건 없네요.
처음부터 끝까지 다 봤는데, 다들 "부하에 따른 유연한 대처"가 방향성이 었습니다.
어마어마한 트래픽을 유지하는데 있어서 평소엔 줄었다가 급작스레 몰릴때는 
AWS가 존트 짱짱 대처를 잘 해줘요.
예외로 뭐... 하두 노후화 되서 옮겼다. 
혹은, 지사 관리를 해야하는데 차라리 AWS하니깐 편하더라.
그리고 나머지는 게임 얘기네요.

처음에는 화장품 업계 관련 정말 살벌하게 찾아 봤지만, 
기존 AWS가 가지고 있는 스케일업, 분산처리에 초점이 많이 맞춰져 있었습니다.

근데, 저는 사실 여전히 AWS를 컨텐츠 제공 업체로 보고 있어서 
AWS가 제공하는 Rekognition, LEX, Polly, Transcribe에 관심이 많습니다.

AWS의 본질 보다도 계속 이걸 어떻게 다른 분야로 응용 할수 있을까만 고민 하고 있습니다.
화장품 업계는 일단 회사 출근해서 봐야 할거 같고 -_-.....

당장 귀동냥으로 들은건 아버지 사업관련 저 부분 밖에 없어서리....
지금도 계속 정리 중이지만, 다이어그램이 완성 되면 나중에 말씀 드리겠습니다.

**Comment by tea7day** [comment]
aws 이슈는 우선 종료하겠습니다. 필요한 자료는 추후 위키로 옮길 예정입니다.
