### ISSUE TITLE
[오프라인] 5차 스터디 정리 - 서버리스, 다이어그램, 슬랙 명령어

### ISSUE THREAD

**Issue by GwangHeon** [echoen/enjoy-aws#21]
○ 서버리스 - 도쿄 리전
◎ 서버리스 셋팅
● 링크
- https://serverless.com/framework/docs/getting-started/

● 이클립스

● node.js : https://nodejs.org/ko/download/

● gradle 설치 
![image](https://user-images.githubusercontent.com/20102683/36071840-8173f988-0f58-11e8-9c7d-65bb1dc61393.png)

● 경로 셋팅
![image](https://user-images.githubusercontent.com/20102683/36071813-1299c362-0f58-11e8-8cac-c052263386b8.png)

![image](https://user-images.githubusercontent.com/20102683/36071817-26d34380-0f58-11e8-9247-490cdf864af2.png)

● 워크 스페이스 셋팅 화면
![image](https://user-images.githubusercontent.com/20102683/36071870-f089fb92-0f58-11e8-9b58-ea44127f247e.png)

● AWS 접근을 위한 ID와 KEY 값 셋팅
![image](https://user-images.githubusercontent.com/20102683/36071831-4a597dc4-0f58-11e8-952b-084786d33f2e.png)

● 빌드 및 배포 명령어
- IAM 권한 필요
![image](https://user-images.githubusercontent.com/20102683/36071737-d87c10aa-0f56-11e8-9226-8168599d5738.png)
- 환경 변수 필요 : 터미널 조작과  deploy를 위하여  (https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html)
![image](https://user-images.githubusercontent.com/20102683/36071867-d9605eb6-0f58-11e8-9ace-2a259e6a49bb.png)

● AWS 화면 (Gateway)  
![image](https://user-images.githubusercontent.com/20102683/36071896-4de9b02a-0f59-11e8-990a-d2a25f1142f9.png)

- URL 있는 곳
![image](https://user-images.githubusercontent.com/20102683/36071902-78fcb096-0f59-11e8-8537-736d9285a397.png)

● 서버리스 최초 링크
- https://github.com/awskrug/aws-serverless-workshops

● 다이어 그램
- https://www.draw.io/?libs=aws2&splash=0

● Slack "/명령어"셋팅
- https://api.slack.com/apps

**Comment by tea7day** [comment]
종료된 스터디이므로 우선 클로즈상태로 관리할게요. 정리 최고~! :)
