### ISSUE TITLE
이미지/영상 인식 기술 활용하기

### ISSUE THREAD

**Issue by tea7day** [echoen/enjoy-aws#22]
이미지나 영상 인식 기술을 활용하는 방법에 대한 이슈입니다.

좋은 자료나 라이브러리, 또는 의견등을 자유롭게 여기서 공유했으면 좋겠습니다. :)

**Comment by GwangHeon** [comment]
어후 구글 이미지 분석 봐봐요 . AWS 돋밥임
![image](https://user-images.githubusercontent.com/20102683/36072135-cc1e2292-0f5d-11e8-85f9-8f6ac8ae3d55.png)

![image](https://user-images.githubusercontent.com/20102683/36072153-059754da-0f5e-11e8-95fb-e32e22a92931.png)

**Comment by tea7day** [comment]
굿이네요! 비슷한 이미지 URL도 뽑아서 보여주는 거죠?

**Comment by GwangHeon** [comment]
네네 GraphiQL을 이용해서 웹 봇? 크롤링은 금방 만들듯요 ㅋㅋㅋ

**Comment by tea7day** [comment]
### 이미지 인식 API 비교
- [Google Vision vs. Amazon Rekognition: A Vendor-neutral Comparison](https://cloudacademy.com/blog/google-vision-vs-amazon-rekognition/)
- [Compare image text recognition apis](https://dataturks.com/blog/compare-image-text-recognition-apis.php)
- [SEARCHING FOR THE BEST COMPUTER VISION API](https://www.topbots.com/chihuahua-muffin-searching-best-computer-vision-api/)
- [Comparing Machine Learning (ML) Services from Various Cloud ML Service Providers](https://medium.com/kontikilabs/comparing-machine-learning-ml-services-from-various-cloud-ml-service-providers-63c8a2626cb6)
- [Comparing Machine Learning as a Service: Amazon, Microsoft Azure, Google Cloud AI](https://www.altexsoft.com/blog/datascience/comparing-machine-learning-as-a-service-amazon-microsoft-azure-google-cloud-ai/)

### 요약
-

**Comment by tea7day** [comment]
aws 이슈는 우선 종료하겠습니다. 필요한 자료는 추후 위키로 옮길 예정입니다.
