### ISSUE TITLE
[오프라인] 6차 스터디 - 이광헌 / 이미지 분석 : 구글 Vision ↔ AWS ↔ slack 연동

### ISSUE THREAD

**Issue by GwangHeon** [echoen/enjoy-aws#23]
https://cloud.google.com/vision/docs/quickstarts?hl=ko

**Comment by GwangHeon** [comment]
https://cloud.google.com/vision/docs/how-to?hl=ko

**Comment by GwangHeon** [comment]
● Curl 작업
- https://cloud.google.com/vision/docs/using-curl?hl=ko
![image](https://user-images.githubusercontent.com/20102683/36087131-01b48cbe-1014-11e8-969c-bc45500cdec1.png)
![image](https://user-images.githubusercontent.com/20102683/36087142-164807e6-1014-11e8-94cb-39ebe33401cf.png)

**Comment by GwangHeon** [comment]
https://cloud.google.com/vision/docs/request?hl=ko

**Comment by GwangHeon** [comment]
https://cloud.google.com/community/tutorials/make-an-http-request-to-the-cloud-vision-api-from-java

**Comment by GwangHeon** [comment]
https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#AnnotateImageRequest

**Comment by GwangHeon** [comment]
![image](https://user-images.githubusercontent.com/20102683/36135190-e03cb64c-10cc-11e8-88d4-706def0ce773.png)

**Comment by GwangHeon** [comment]
![image](https://user-images.githubusercontent.com/20102683/36151146-8bc56658-1109-11e8-8046-6c846697d909.png)

**Comment by GwangHeon** [comment]
JSON 추가
http://yoo-hyeok.tistory.com/36

**Comment by GwangHeon** [comment]
![image](https://user-images.githubusercontent.com/20102683/36188148-8c1c8d1e-118d-11e8-9306-ed4cc4d0c2b2.png)

**Comment by GwangHeon** [comment]
■ 이미지 분석 : 구글 Vision ↔ AWS ↔ slack 연동
● 흐름
 
![image](https://user-images.githubusercontent.com/20102683/36191576-35396620-11a1-11e8-8de0-6d39dc2accdb.png)

● 슬랙
○ 입력 폼
 
![image](https://user-images.githubusercontent.com/20102683/36191579-37f6a8aa-11a1-11e8-9fc0-c656db622dc2.png)

/google_vision_test http://img.insight.co.kr/static/2018/02/08/700/y4c438n7p9k9smll2i3o.jpg

○ 명령어 생성
1) Create New App
![image](https://user-images.githubusercontent.com/20102683/36191590-408c8e58-11a1-11e8-8331-3df1e192fd99.png)

2) new slash command
![image](https://user-images.githubusercontent.com/20102683/36191602-482d1fce-11a1-11e8-86e4-98f1cc46b6bd.png)

3) request URL 셋팅
![image](https://user-images.githubusercontent.com/20102683/36191611-4f91c706-11a1-11e8-9bec-11e56aa6f3f8.png)

● Serverless – AWS API gateway와 AWS Lambda 셋팅
1) 승현님이 셋팅해놓으신 /boilerplate 안에 있는 걸로 사용중
2) 이클립스로 열 때, 첫 화면에서 전혀 상관없는 폴더를 열고,
![image](https://user-images.githubusercontent.com/20102683/36191620-5ad3bcf0-11a1-11e8-892c-85dbaa3b6560.png)
3) 이클립스에서 import 할때, gradle로 연다.
![image](https://user-images.githubusercontent.com/20102683/36191625-615f14ca-11a1-11e8-9e65-6b3ed549d42e.png)
4) 그럼 우린, handler를 맞이 할 수 있습니다. 여기서 코드수정
![image](https://user-images.githubusercontent.com/20102683/36191630-6846e29a-11a1-11e8-8e64-0082cf9bf361.png)

○ AWS 접근 셋팅 및 빌드, 배포.
![image](https://user-images.githubusercontent.com/20102683/36191635-6f2fe23c-11a1-11e8-9c1e-4187946728d9.png)
※ 아름답게 람다에 설치가 됨. 그러나 코드는 볼수가 음슴

● API Gateway 셋팅
1) 경로명을 serverless 명과 같게(serverless.yml의 service명과 같아야함) 하고, post를 만들어줌
- 가장 중한건, API 배포 하는거 관련해서 셋팅 하는 것
![image](https://user-images.githubusercontent.com/20102683/36191641-7845952e-11a1-11e8-86c3-8763e3338d09.png)
2) 배포 스테이지는 serverless.yml에 있는 stage 참고
![image](https://user-images.githubusercontent.com/20102683/36191646-7e301f7c-11a1-11e8-8d10-ecb50e737035.png)
3) 스테이지 셋팅도 마찬가지
- 여기서 URL 호출은 슬랙에서 RequestURL과 같아야만 한다.
![image](https://user-images.githubusercontent.com/20102683/36191651-847d7528-11a1-11e8-9ee4-e6a9fb532c35.png)
4) 테스트 가능
![image](https://user-images.githubusercontent.com/20102683/36191655-8bb5f658-11a1-11e8-897c-e4b6595952a3.png)

● 구글 vision 셋팅
※ 가장 중한건, API 접근을 위한 키값이 필요합니다. 그리고 나머지는 그냥 URL 호출만 하면 됨
![image](https://user-images.githubusercontent.com/20102683/36191660-935f8ae0-11a1-11e8-80b9-57b19a2a95ae.png)
![image](https://user-images.githubusercontent.com/20102683/36191661-95dc556e-11a1-11e8-9560-15466fb43247.png)

○ 관련 URL
1) 한번쯤 읽어보시는게… - quick start
https://cloud.google.com/vision/docs/quickstarts?hl=ko

2) cURL 실행
https://cloud.google.com/vision/docs/auth?hl=ko
![image](https://user-images.githubusercontent.com/20102683/36191670-9f3403be-11a1-11e8-8532-b1c5c950a1eb.png)
![image](https://user-images.githubusercontent.com/20102683/36191673-a1f747aa-11a1-11e8-981b-1d26d26f40ac.png)

3) 요청 실행 포맷
https://cloud.google.com/vision/docs/request?hl=ko

4) 요청 실행 테스트 하는 곳
https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#AnnotateImageRequest

5) 자바에서 코드 구성하는 방법
https://cloud.google.com/community/tutorials/make-an-http-request-to-the-cloud-vision-api-from-java

● 코드 구성
- 이것은 실제로 코드를 보면서…..

● 로그 확인 
- cloudwatch에서 다음과 같이 확인 할수 있음.
![image](https://user-images.githubusercontent.com/20102683/36191678-a93c20e4-11a1-11e8-9196-63a421d970e3.png)

● 슬랙으로 쏴주는 모습
- 3초 리미트가 간당간당함
![image](https://user-images.githubusercontent.com/20102683/36191684-af8d4c16-11a1-11e8-8173-18860d58d58c.png)

**Comment by tea7day** [comment]
훌륭하십니다!

**Comment by tea7day** [comment]
수고하셨습니다!
구글 비전 API 따라해보면서 적용해봐야겠습니다. ㅎㅎ

소스코드도 깃허브올려주시면 참고할께요!

**Comment by GwangHeon** [comment]
https://drive.google.com/file/d/16WGp0AgR_RzkF9clm5_Gf2ufcVMzB8c1/view?usp=sharing

링크 올렸습니다

**Comment by tea7day** [comment]
aws 이슈는 우선 종료하겠습니다. 필요할 때 이슈를 다시 오픈해주세요.
