### ISSUE TITLE
AWS  스터디 - 4차

### ISSUE THREAD

**Issue by tea7day** [echoen/enjoy-aws#8]
### 일시

- 01/19(금) 7:30~10:30
- 구의역 스타벅스 또는 광헌형님 집 

### 내용

- 서비스 훑어보기: [SNS](https://aws.amazon.com/sns/)
- 아키텍처 리뷰: [비트윈](http://engineering.vcnc.co.kr/2013/04/between-system-architecture)
- 서버리스:  보일러플레이트 리뷰 및 첫 번째 람다 앱
- 의견(승현): AWS [자격증](https://aws.amazon.com/certification/certified-developer-associate/) 준비

**Comment by TRQ1** [comment]
자격증 준비에 대해서는 전에 보던 사이트를 이용하는게 어떨까요?

**Comment by tea7day** [comment]
좋아~~ #7 여기다가 댓글로 사이트링크랑 정보를 모으자구~!

**Comment by tea7day** [comment]
## 비트윈 블로그중 몰랐던 내용

### Apache Thrift
- [Thrift Home](https://thrift.apache.org/)
- [RPC - Apache Thrift 입문 1부](http://blog.appkr.kr/work-n-play/how-to-use-apache-thrift-in-php-part-1/)

**Comment by tea7day** [comment]
java&lambda에서 aws apigateway 용 req/resp 객체 사용법 
- http://willhamill.com/2016/12/12/aws-api-gateway-lambda-proxy-request-and-response-objects

**Comment by tea7day** [comment]
### 4차 스터디 내용 정리

#### 강의식 스터디 진행에 대한 의견 나눔
- 진행자의 부담이 있고, 듣는 위주의 수동적인 스터디는 직접 실습보다 클라우드 기술 습득에 효율성이 낮음 

#### 앞으로 진행 방향 (5차~)
- 컨텐츠를 정하고 **클라우드를 활용하여 작동하는 어플리케이션을 구성**하는 것을 목표로 함
  - 컨텐츠: 슬랙 이미지 인식 챗봇 (슬랙에 이미지를 업로드하면 해당 이미지의 영문자를 확인하여 슬랙메세지로 답장을 해줌)
- 슬랙과 AWS를 기반 플랫폼으로 시작해서 어플리케이션의 기능을 점점 확장해나가기로 함
- 오프라인 모임은 각자 개발 진행 정도에 따라 일정을 협의하기로 함 (요일 고정x)
- 온라인에서의 커뮤니케이션을 적극 활용하며, 슬랙과 깃허브 이슈를 기반으로 진행함
